### ISSUE TITLE
Make our CI build wheels against TF 2.1 and 2.2

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/addons#1458] opened 2020-03-27 10:44 UTC
**Describe the feature and the current behavior/state.**

Currently in the CI, we test against tf 2.2 only on linux with python 3.5 and without releasing the wheels.

We should build wheels against 2.1 and 2.2, and push the wheels for tf 2.1 to pypi, then when 2.2 is stable, we should start pushing the wheels for tf 2.2 to pypi.

**Relevant information**
- Are you willing to contribute it (yes/no): yes
- Are you willing to maintain it going forward? (yes/no): yes
- Is there a relevant academic paper? (if so, where): no
- Is there already an implementation in another framework? (if so, where): no
- Was it part of tf.contrib? (if so, where): no

**Which API type would this fall under (layer, metric, optimizer, etc.)**

CI

**Who will benefit with this feature?**

Users who will be able to use the python part of addons with tf 2.1 and 2.2.

**Any other info.**

There are two parts to this issue, one that we can do now and one where we may have to wait for the custom ops docker image to be released for tf 2.2.

**Comment by seanpmorgan** [comment] 2020-03-27 13:24
Hmmm would like to carfefully think about how we version this? 0.8.x pinned to TF2.1 and 0.9.x pinned to TF2.2? How long do we support older TF versions?

**Comment by gabrieldemarmiesse** [comment] 2020-03-27 14:05
That may be a topic to add to the meeting next week. The way I see it:

>  0.8.x pinned to TF2.1 and 0.9.x pinned to TF2.2?

We have two things here. Python API compatibility and ABI compatibility. 

* The ABI is compatible with a single wheel not even a full tensorflow version because when building tf from source or when using a nightly, it's not garanteed that it works. Even TF increasing the minor version can potentially break the ABI. We can see that we can't use the ABI compatibility to dictate what we support overall. It's way too strict.
* The python API compatibility is a lot easier to respect. As long as we use the TF public API, we'll be forward compatible, even with nightlies as long as TF doesn't introduce bugs. For backward compatibility, my take is that as long as it's not painful, we should keep it. Meaning, if someone comes forward and wants to merge a feature that requires a version of tensorflow strictly higher than the oldest one we support, that may be a good time to discuss dropping support for an older version of TF.

Using this principle, we could support way more than 2 TensorFlow versions, it's just more jobs in the build matrix. Similar to the versions of python we support. 

I understand that TensorFlow projects in general have more a vision of "everything targets HEAD and being compatible with old versions is not important" but the rest of the world doesn't do that. From my undestanding, this is inherited by Google's monorepo philosophy. It's not necessarily good or bad, it depends on where the user is working. Users of open source software don't expect packages to force them to use a specific version for a dependency. 

### ABI compatibility matrix:

tfa 8.x -> TF2.1.0   # if TF releases 2.1.1, we might have to do a minor release too to recompile.
tfa 9.x -> TF 2.2.0   
tfa 10.x -> TF (whatever is the most recent stable version)

### Python compatibility matrix:

x can be any number

tfa 8.x -> TF 2.1.x 
tfa 9.x -> TF 2.1.x and TF 2.2.x 
tfa 10.x ->TF 2.1.x and TF 2.2.x (and TF 2.3.x depending on our release scheduler)

We should continue supporting TF 2.1.x on the python side as long as it's not painful. If there is some pain point in any way, we'll drop it.

@tensorflow/sig-addons-maintainers what do you think?

**Comment by seanpmorgan** [comment] 2020-03-27 14:34
> That may be a topic to add to the meeting next week. 

Agree, it's a substantial decision that dictates how we run the repo going forward.

> > 0.8.x pinned to TF2.1 and 0.9.x pinned to TF2.2?

> We can see that we can't use the ABI compatibility to dictate what we support overall. It's way too strict.

Agree, and we have removed the install dependency for any specific tf version because of this. If we keep a single TF version for custom-ops that doesn't prevent python users from upgrading TFA while using an older TF core version.

>  Meaning, if someone comes forward and wants to merge a feature that requires a version of tensorflow strictly higher than the oldest one we support, that may be a good time to discuss dropping support for an older version of TF.

If we go this route then I like this method for dropping support but don't love it. There's no guarantee to users for how long their TF core version will be supported. Custom-op users may abruptly find out their tf core version is dropped from support. The current method doesn't keep them up to date with new custom-ops but at least that'll be known ahead of time.


> Using this principle, we could support way more than 2 TensorFlow versions, it's just more jobs in the build matrix. Similar to the versions of python we support.

Yeah I'm not worried so much about testing multiple versions, but rather the maintence burden this puts on us. We'll need to backport all fixes and new features to the repo to multiple branches (conceivably up to like 15 branches based on TF1 versioning). We'll also need to release a different minor version on all of those branches. It's do-able with the automation we have in place but is not an insignificant amount of work.

The current comaptibility matricies would be :

### ABI compatibility matrix:
tfa 8.x -> TF2.1.0 # if TF releases 2.1.1, we might have to do a minor release too to recompile.
tfa 9.x -> TF 2.2.0
tfa 10.x -> TF (whatever is the most recent stable version)

### Python compatibility matrix:
tfa 8.x >= TF 2.1
tfa 9.x >= TF 2.1
tfa 10.x >= TF 2.1
 
The only issue with doing this is how to test only python ops without custom-ops failing in CI for newer versions.

**Comment by gabrieldemarmiesse** [comment] 2020-03-27 15:31
So I had a quick call we @seanpmorgan  and we agree on what to do, but it's just that we wasn't clear enough in our messages. I'll try to sum up what we discussed here. @seanpmorgan feel free to edit my message if you think it improves clarity.

## Warnings

Since the compatibility with TF is not managed at the pip level, we need to add warnings ourselves about what we support. There will be two warnings:

* One warning that we throw when the user is trying to load a shared object file with an unsupported version of tensorflow . Only a few specific wheels are compatible here, so it's a strict version check, for example `assert 2.1 <= tf.__version__ < 2.2`.
* One warning that we throw at import time, when we know the version of tensorflow used by the user is not compatible with Addons on the Python side. For example for Addons 0.9.x, this warning will trigger only when the TF version is not 2.1.x or 2.2.x. Since we currently use private TF APIs in some user-facing code, we have to put an upper bound on the version we support on the python side. When Addons will be freed of private TF APIs in the user-facing code, we'll relax the requirement on the upper bound (e.g. `if tf.__version__ < 2.2.0: warning.warn(...)`).

## Support of branches.

At any given time we support 2 branches:

* The master branch of course
* The latest stable branch. Currently the 0.8 branch. Soon we'll create the 0.9 branch and drop support for the 0.8 at the same time.

Each of those branch support a range of TF version on the Python side. This range is constant for a given stable branch, but in the master branch, this range can vary and we won't give warnings as when to swich. Since we upload the nightlies at each commit of the master branch, the supported versions of TF can change abruptly in the nightlies.

The same is true for our support of the TF versions on the ABI side. The only difference is that the range of TF versions we'll support will be much smaller.

**Comment by gabrieldemarmiesse** [comment] 2020-03-31 11:38
What is currently missing is the docker image to build the manylinux wheels for 2.2.0. It's likely that this docker image will be available after the stable release.

**Comment by seanpmorgan** [comment] 2020-04-22 01:02
We're currently building and testing TF 2.1 and 2.2 wheels. The switch to publishing wheels built from 2.2 will happen once we get a stable release.

Regarding the 2.2-custom-op docker image. We'll want to use this when available, but we've currently updated our minimal docker image to support py38 and it's working as intended. Closing.

**Closed by seanpmorgan** 2020-04-22 01:02 UTC
Labels: discussion needed
