### ISSUE TITLE
Add "Project Description" when publishing to PyPI

### ISSUE THREAD

**Issue by huan** [tensorflow/addons#127] opened 2019-04-02 07:57 UTC
If we goto PyPI module page https://pypi.org/project/tensorflow-addons/, we will not see any document about this module: It's empty.

We should add a project description to this page so that the developer could be able to understand what this module is easier.

**Comment by seanpmorgan** [comment] 2019-04-02 12:19
Thanks @huan! Just created this a few days ago though so duplicate of #114

**Closed by seanpmorgan** 2019-04-02 12:19 UTC

**Comment by huan** [comment] 2019-04-02 16:20
@seanpmorgan Great! sorry for having not noticed that old one.
