### ISSUE TITLE
No matching distribution found for tensorflow-addons

### ISSUE THREAD

**Issue by ShwetaTiwariRepo** [tensorflow/addons#2507] opened 2021-06-21 18:18 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): M1 Chip
- TensorFlow version and how it was installed (source or binary): tensorflow-macos       version 2.5.0
- TensorFlow-Addons version and how it was installed (source or binary): not able to install
- Python version: 3.9.4
- Is GPU used? (yes/no):

**Describe the bug**
i am trying to install tensorflow addons using "pip install tensorflow-addons" but it throws up the error 
ERROR: Could not find a version that satisfies the requirement tensorflow-addons (from versions: none)
ERROR: No matching distribution found for tensorflow-addons

**Comment by bhack** [comment] 2021-06-21 18:36
It is a duplicate of https://github.com/tensorflow/addons/issues/2503

**Closed by bhack** 2021-06-21 18:36 UTC
Labels: duplicate, macos

**Comment by EdgeCyrus** [comment] 2024-10-04 08:40
same
