### ISSUE TITLE
Request: Examples/Tutorials required for seq2seq NMT model 

### ISSUE THREAD

**Issue by John-8704** [tensorflow/addons#724] opened 2019-11-30 07:54 UTC
It would be really helpful if there were examples on how to build basic keras seq2seq models (NMT) and make predictions/inference with attention and beam search implemented from tensorflow addons. I couldn't find any examples/tutorials regarding this.  I couldn't figure out how to use it.

**Comment by Om-Pandey** [comment] 2019-12-01 11:30
Would you like to solve it ?... or assign the issue to me if you like

**Comment by John-8704** [comment] 2019-12-01 14:58
I don't think I can solve this. If you like to contribute can you check this open issue [here](https://github.com/tensorflow/addons/issues/335). For explanation regarding submission of tutorial you could check @kazemnejad fork [here](https://github.com/kazemnejad/addons/tree/seq2seq_example_draft/docs/tutorials).

**Comment by seanpmorgan** [comment] 2019-12-01 15:51
I'm going to close this as it's more or less a duplicate of #335. @Om-Pandey would you be willing to contribute a tutorial for that issue?

**Closed by seanpmorgan** 2019-12-01 15:51 UTC

**Comment by Om-Pandey** [comment] 2019-12-01 18:40
@seanpmorgan Sure
