### ISSUE TITLE
Any example to use CRF on custom training 

### ISSUE THREAD

**Issue by pinedbean** [tensorflow/addons#2052] opened 2020-07-28 10:39 UTC
I'm googling a lot of example of BiLSTM-CRF 

but can't find an example one to do BiLSTM-CRF on tensorflow 2.2+ 

I also try to import 
from tensorflow_addons.layers import CRF 

but it can't find CRF

**Comment by bhack** [comment] 2020-07-28 10:45
Have you looked at https://stackoverflow.com/questions/59019290/how-to-add-crf-layer-in-a-tensorflow-sequential-model?

**Comment by bhack** [comment] 2020-07-28 10:46
This could be also a duplicate of:
https://github.com/tensorflow/addons/issues/337
https://github.com/tensorflow/addons/issues/1769

**Comment by pinedbean** [comment] 2020-07-28 10:53
Yes, I'm looking on that one already 

Here is what I try to implement 

CRF 
```
log_likelihood, self.transition_params = tfa.text.crf_log_likelihood(logits,
label_sequences,
text_lens,
transition_params=self.transition_params)
```

And  decode as 
```
viterbi_path, _ = tfa.text.viterbi_decode(logit, model.transition_params)
``` 

But the result seem incorrect (all possibility go from 'O' -> 'O' when decode (try to do NER)

I'm not sure that I implement it correct or not

**Comment by bhack** [comment] 2020-07-28 11:11
There are already two tickets about CRF example/documentation request. Please post there.

**Closed by bhack** 2020-07-28 11:11 UTC
Labels: crf
