### ISSUE TITLE
tfa.activations.rrelu

### ISSUE THREAD

**Issue by zjuter0126** [tensorflow/addons#1873] opened 2020-05-22 15:45 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow version and how it was installed (source or binary):
- TensorFlow-Addons version and how it was installed (source or binary):
- Python version:
- Is GPU used? (yes/no):

**Describe the bug**

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by zjuter0126** [comment] 2020-05-22 15:46
when use tfa.activations.rrelu in Tensorflow.keras   some mistakes happend
        x = self.conv_1D(inputs)
        x = self.bn1_1D(x, training=training)
        x =  tfa.activations.rrelu(x,training=training)
        x = self.pool_1D(x)

ValueError: Input 0 of layer batch_normalization is incompatible with the layer: its rank is undefined, but the layer requires a defined rank

**Comment by WindQAQ** [comment] 2020-05-24 17:14
Hi @zjuter0126, sorry for the late reply, could you provide a runnable code snippet so that we can diagnose where the problem is? Thank you!

**Comment by seanpmorgan** [comment] 2020-07-16 02:26
Closing due to lack of information. Please let us know if you have a reproducible code sample and we'll look into it.

**Closed by seanpmorgan** 2020-07-16 02:26 UTC
Labels: activations
