### ISSUE TITLE
0.8.2, 0.8.1 version is not compatible with Mac OS version < 10.15

### ISSUE THREAD

**Issue by nbowon** [tensorflow/addons#1108] opened 2020-02-19 14:49 UTC
**Describe the feature and the current behavior/state.**
I'm using Mac OS 10.14.6 version and I cannot install 0.8.2 or 0.8.1 version with pip
Seems 0.8.2 is only compatible with Mac OS version 10.15.x
Could you make 0.8.2 version of tensorflow-addons compatible with Mac OS 10.14.x?

**Relevant information**
- Are you willing to contribute it (yes/no): no
- Are you willing to maintain it going forward? (yes/no): yes
- Is there a relevant academic paper? (if so, where): no
- Is there already an implementation in another framework? (if so, where): no
- Was it part of tf.contrib? (if so, where): I'm not sure

**Which API type would this fall under (layer, metric, optimizer, etc.)**

**Who will benefit with this feature?**
anyone who are using Mac OS 10.13, 10.14 version

**Any other info.**

**Comment by seanpmorgan** [comment] 2020-02-19 15:50
Thanks for the issue! So the reason for this is when we switched builds to GitHub actions we didn't notice that the MacOS environment was running 10.15. Previously we had built for 10.13. 

Simple fix just need to copy TF-IO's stratefgy:
https://github.com/tensorflow/io/blob/master/.github/workflows/build.yml#L81-L82

**Comment by seanpmorgan** [comment] 2020-02-20 01:45
@nbowon Could you please try to install `tfa-nightly` and see if it works. The pip package is still labeled as 10.15 but I'm not sure if pip prevented you from installing it or if the package crashed on older versions.

Re-opening this until it's confirmed to be fixed. Once it is we will create a 0.8.3 patch release.

**Comment by nbowon** [comment] 2020-02-20 03:07
I can install tfa-nightly,
when I try 
> pip install tfa-nightly

> tfa-nightly-0.8.0.dev20200125
is installed. 
I still cannot install 0.8.2 version

**Comment by seanpmorgan** [comment] 2020-02-20 03:13
As a short term option you can build Addons from source:
https://github.com/tensorflow/addons#installing-from-source

We'll continue to work to get the packages fixed though. Please follow along with this issue.

@yongtang just FYI it appears that TF-IO packages are being built against 10.15 as well since moving to GitHub actions:
https://pypi.org/project/tensorflow-io-nightly/#files

**Comment by yongtang** [comment] 2020-02-20 03:24
@seanpmorgan Thanks! I think the issue happens in setup tools. As `python setup.py...` creates the package with `macosx_10_15` shown up in the filename of `whl` created. May need to look into setuptools package to see if there is a ways to pass the expected name instead. Otherwise the build may have to happen on macOS 10.13.

**Comment by yongtang** [comment] 2020-02-20 03:39
Looks like there is a `--plat-name` in setup tools that could be used to specify a different platform:

```
Options for 'build' command:
....
  --plat-name (-p)   platform name to build for, if supported (default: macosx
                     -10.15-x86_64)
  --compiler (-c)    specify the compiler type
....
```

**Comment by yongtang** [comment] 2020-02-20 04:42
@seanpmorgan I created a PR #797 for tensorflow/io. Think it might work on add-on as well.

Still need to find out a way to sanity check to make sure the generated binary works on 10.13.

**Comment by nbowon** [comment] 2020-02-20 06:21
@nbowon seanpmorgan Thanks. I'm trying to use it by building from source. 
I hope it will resolve soon.

**Comment by yongtang** [comment] 2020-02-20 18:55
@seanpmorgan adding the following line will resolve the issue on addon:
```
--plat-name macosx_10_13_x86_64
```

**Closed** 2020-02-21 15:31 UTC
Labels: bug, build

**Comment by seanpmorgan** [comment] 2020-02-22 13:01
@nbowon When you get a chance could you try pip installing `tfa-nightly` and seeing how it works now. Packages look to support 10.13 now:
https://pypi.org/project/tfa-nightly/#files

**Comment by nbowon** [comment] 2020-02-22 14:11
@seanpmorgan I can install tea-nightly-0.9.0.dev20200222 version and it is labeled with machos_10_13
looks like it worked. 
Thank you
