### ISSUE TITLE
Build fails on tf-nightly due to new protobuf

### ISSUE THREAD

**Issue by armando-fandango** [tensorflow/addons#165] opened 2019-04-11 13:22 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): custom-op container
- TensorFlow installed from (source or binary):  custom-op container
- TensorFlow version (use command below):  custom-op container
- TensorFlow Addons installed from (source, PyPi):  custom-op container
- TensorFlow Addons version:  latest master branch
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc):  custom-op container
- Bazel version (if compiling from source):  custom-op container
- GCC/Compiler version (if compiling from source):  custom-op container
- Is GPU used? (yes/no): no
- GPU model (if used): no

**Describe the bug**

Build fails in freshly downloaded custom-ops container.

Example log:
```
ERROR: /addons/tensorflow_addons/custom_ops/seq2seq/BUILD:5:1: Couldn't build file tensorflow_addons/custom_ops/seq2seq/_objs/_beam_search_ops.so/1/beam_search_ops.pic.o: C++ compilation of rule '//tensorflow_addons/custom_ops/seq2seq:_beam_search_ops.so' failed (Exit 1): gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/e051f2f195071208ea7f081f88730f4f/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    TF_HEADER_DIR=/usr/local/lib/python2.7/dist-packages/tensorflow/include \
    TF_SHARED_LIBRARY_DIR=/usr/local/lib/python2.7/dist-packages/tensorflow \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/tensorflow_addons/custom_ops/seq2seq/_objs/_beam_search_ops.so/1/beam_search_ops.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow_addons/custom_ops/seq2seq/_objs/_beam_search_ops.so/1/beam_search_ops.pic.o' -fPIC -iquote . -iquote bazel-out/k8-opt/genfiles -iquote bazel-out/k8-opt/bin -iquote external/local_config_tf -iquote bazel-out/k8-opt/genfiles/external/local_config_tf -iquote bazel-out/k8-opt/bin/external/local_config_tf -iquote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -iquote bazel-out/k8-opt/bin/external/bazel_tools -isystem external/local_config_tf/include -isystem bazel-out/k8-opt/genfiles/external/local_config_tf/include -isystem bazel-out/k8-opt/bin/external/local_config_tf/include -pthread '-std=c++11' '-D_GLIBCXX_USE_CXX11_ABI=0' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow_addons/custom_ops/seq2seq/cc/ops/beam_search_ops.cc -o bazel-out/k8-opt/bin/tensorflow_addons/custom_ops/seq2seq/_objs/_beam_search_ops.so/1/beam_search_ops.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
In file included from bazel-out/k8-opt/genfiles/external/local_config_tf/include/tensorflow/core/framework/op_def_builder.h:24:0,
                 from bazel-out/k8-opt/genfiles/external/local_config_tf/include/tensorflow/core/framework/op.h:23,
                 from tensorflow_addons/custom_ops/seq2seq/cc/ops/beam_search_ops.cc:16:
bazel-out/k8-opt/genfiles/external/local_config_tf/include/tensorflow/core/framework/op_def.pb.h:10:40: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
```

**Describe the expected behavior**

`make` should pass all tests

**Code to reproduce the issue**

NA

**Other info / logs**

NA

**Comment by armando-fandango** [comment] 2019-04-11 13:25
Caused due to this: https://github.com/tensorflow/tensorflow/issues/27697

**Comment by seanpmorgan** [comment] 2019-04-11 13:29
Not related to custom_op container. This is a bug in tensorflow nightly

**Comment by armando-fandango** [comment] 2019-04-11 14:17
I saw someone put the fix in the TF issue but not pull request, would it be considered code-piracy if I take that code snippet and submit a pull request for TF so we can move on faster :-)

**Comment by seanpmorgan** [comment] 2019-04-11 14:24
The code snippet in that issue is pointing to the problem, but it does not include a fix. Once a PR is merged we'll need to wait until the following nightly is published.

**Comment by armando-fandango** [comment] 2019-04-11 18:12
> The code snippet in that issue is pointing to the problem, but it does not include a fix. Once a PR (that includes regex for `.inc`) is merged we'll need to wait until the following nightly is published.

Yes, I misspoke, I meant if I take that hint. :-)

**Comment by kyleabeauchamp** [comment] 2019-04-27 01:39
Can we re-open this issue?  I'm getting the same error on the 4/26 GPU nightly.  The problem goes away if I revert to 4/24 GPU or to the CPU nightly.  

```
rm -rf ~/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_addon*
rm -fr ~/.cache/
./configure.sh
bazel build build_pip_pkg
bazel-bin/build_pip_pkg artifacts
pip install artifacts/tensorflow_addons-*.whl
[...]


ERROR: ~/src/forks/addons/tensorflow_addons/custom_ops/image/BUILD:7:1: C++ compilation of rule '//tensorflow_addons/custom_ops/image:_distort_image_ops.so' failed (Exit 1) x86_64-conda_cos6-linux-gnu-cc failed: error executing command ~/miniconda3/envs/tf2/bin/x86_64-conda_cos6-linux-gnu-cc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD ... (remaining 40 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from bazel-out/k8-fastbuild/genfiles/external/local_config_tf/include/tensorflow/core/framework/tensor_shape.h:22:0,
                 from bazel-out/k8-fastbuild/genfiles/external/local_config_tf/include/tensorflow/core/framework/partial_tensor_shape.h:20,
                 from bazel-out/k8-fastbuild/genfiles/external/local_config_tf/include/tensorflow/core/framework/attr_value_util.h:23,
                 from bazel-out/k8-fastbuild/genfiles/external/local_config_tf/include/tensorflow/core/framework/node_def_util.h:22,
                 from bazel-out/k8-fastbuild/genfiles/external/local_config_tf/include/tensorflow/core/framework/shape_inference.h:20,
                 from bazel-out/k8-fastbuild/genfiles/external/local_config_tf/include/tensorflow/core/framework/common_shape_fns.h:20,
                 from tensorflow_addons/custom_ops/image/cc/ops/distort_image_ops.cc:16:
bazel-out/k8-fastbuild/genfiles/external/local_config_tf/include/tensorflow/core/framework/types.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The following `requirements.txt` diff is the latest GPU version that works for me:

```
+tf-nightly-gpu-2.0-preview==2.0.0.dev20190424
```

**Comment by facaiy** [comment] 2019-04-27 01:44
Yesterday Sean mentioned that:
> Yeah, looks like the final fix will be in tomorrow's nightly:
> tensorflow/tensorflow#27697

Sure, let's reopen it now

**Comment by seanpmorgan** [comment] 2019-04-27 13:08
Looks fixed :D

**Closed by seanpmorgan** 2019-04-27 13:08 UTC
Labels: bug

**Comment by kyleabeauchamp** [comment] 2019-04-27 15:45
confirmed
